export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const CREATE_TUTORIAL = "CREATE_TUTORIAL";
export const RETRIEVE_TUTORIALS = "RETRIEVE_TUTORIALS";
export const UPDATE_TUTORIAL = "UPDATE_TUTORIAL";
export const DELETE_TUTORIAL = "DELETE_TUTORIAL";
export const DELETE_ALL_TUTORIALS = "DELETE_ALL_TUTORIALS";

export const SET_PARAMS = "SET_PARAMS";
export const SET_MODELS = "SET_MODELS";
export const SET_GENERATIONS = "SET_GENERATIONS";
export const CLEAR_PARAMS = "CLEAR_PARAMS";

export const SET_OFFERS = "SET_OFFERS";
export const SET_SEARCH_PARAMS = "SET_SEARCH_PARAMS";
export const SET_SEARCH_MODELS = "SET_SEARCH_MODELS";
export const SET_SEARCH_GENERATIONS = "SET_SEARCH_GENERATIONS";
export const CLEAR_SEARCH_PARAMS = "CLEAR_SEARCH_PARAMS";

export const SET_OFFER = "SET_OFFER";
export const CLEAR_OFFER = "CLEAR_OFFER";

export const SET_ARTICLE = "SET_ARTICLE";
export const CLEAR_ARTICLE = "CLEAR_ARTICLE";